### ISSUE TITLE
Ctrl + C in repl mode results in Segmentation fault

### ISSUE THREAD

**Issue by Vaimer9** [Redfire75369/spiderfire#15]
From Ubuntu, zsh, have the current pre-release binary,
When i press Ctrl + C 2 times in repl mode i get the following:
```
> ^C
Press Ctrl+C again to exit.
^Cmozilla::detail::MutexImpl::~MutexImpl: pthread_mutex_destroy failed: Device or resource busy
[2]    12204 segmentation fault (core dumped)  /home/v9/Downloads/spidey/spiderfire repl
```

**Comment by sagudev** [comment]
On windows it is working normally:
```
C:\>spiderfire repl
> hi
Uncaught exception at inline.js:1:1 - hi is not defined
> let a = "hi"
undefined
> a
hi
> >
C:\>
```

**Comment by Redfire75369** [comment]
That output on windows technically has a bug.
It should require two presses of `Ctrl + C` before exiting. However, this line of code has `true` instead of `false`, meaning that after an entry into the REPL, only one `Ctrl + C` is required. (There's another bug when it's `false`, but I'm working on that one.
https://github.com/Redfire75369/spiderfire/blob/361a4d09976230e2e5058f329e44dd9efae377b2/cli/src/commands/repl.rs#L73

**Comment by Redfire75369** [comment]
This is now fixed due to the implementation of `rustyline` for the REPL. <https://github.com/Redfire75369/spiderfire/commit/df18729a3be3ec780d2bbd48c549f4ac3b6e8130>
